/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.4/samples
 */
plugins {
    kotlin("jvm") version "1.9.24"
    application
}

repositories {
    mavenCentral()
}

application {
    // In Kotlin, a file named Main.kt containing a top-level main() 
    // function compiles into a class named MainKt
    mainClass.set("MainKt")
}
